"""
Interactive Dashboard: Visualizing processed WorldPop data.
"""
import streamlit as st
import pandas as pd
import plotly.express as px
import geopandas as gpd

# 1. Page Configuration
st.set_page_config(page_title="WorldPop Demographics", layout="wide")
st.title("Kenya & Uganda Population Demographics")

# 2. Data Caching (Critical for speed)
@st.cache_data
def load_data():
    # Tomorrow: Load the CSV generated by pipeline.py
    # df = pd.read_csv("data/processed_population.csv")
    # return df
    pass

@st.cache_data
def load_boundaries():
    # Tomorrow: Load GeoJSON for the choropleth map
    pass

# df = load_data()

# 3. Sidebar Filters
st.sidebar.header("Filters")
# Tomorrow: st.sidebar.selectbox("Country", df["Country"].unique())
# Tomorrow: st.sidebar.selectbox("Age Group", df["Age"].unique())
# Tomorrow: st.sidebar.radio("Sex", ["All", "M", "F"])

# 4. Layout & Visualizations
col1, col2 = st.columns(2)

with col1:
    st.subheader("Population Pyramid")
    # Tomorrow: Plotly bar chart (Males positive, Females negative)

with col2:
    st.subheader("Population Density Map")
    # Tomorrow: px.choropleth_mapbox()